# Book settings
title: Notes on Orbital Mechanics for Engineering Students
author: Bryan Weber
logo: hohmann.png

latex:
  latex_documents:
    targetname: book.tex

# execute:
#   execute_notebooks: force

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          vector: ["\\vec{#1}", 1]
          uvec: ["\\hat{#1}", 1]
          mag: ["\\lVert#1\\rVert", 1]
          cross: "\\times"
          unit: ["#1~\\mathrm{#2}", 2]
    # MathJax 3 + Sphinx cannot currently use custom macros as defined here
    # See: https://github.com/executablebooks/jupyter-book/issues/963
    # and: https://github.com/executablebooks/jupyter-book/issues/917
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


parse:
  myst_extended_syntax: true
